[package]
name = "umbrella"
version = "0.1.0"
authors = ["Kyle McKean <mckean.kylej@gmail.com>"]

[dependencies]
nom = "3.*"
serde = "1.0.*"
serde_derive = "1.0.*"
bincode = "1.0.*"
bitflags = "1.0.*"
bit-vec = "0.4.*"
