[package]
name = "beach"
version = "0.1.0"
authors = ["Kyle McKean <mckean.kylej@gmail.com>"]

[dependencies]
itertools = "0.*"
nom = "3.*"
rustyline = { git = "https://github.com/kkawakam/rustyline" }
umbrella = { path = "../umbrella" }
